[libraries]
android-gradlePlugin = "com.android.tools.build:gradle:8.1.4"

androidx-annotation = "androidx.annotation:annotation:1.7.1"
androidx-startup = "androidx.startup:startup-runtime:1.1.1"
androidx-test-core = "androidx.test:core:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-ext-junit = "androidx.test.ext:junit:1.1.5"

gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.27.0"

jodaTime = "joda-time:joda-time:2.12.7"

junit = "junit:junit:4.13.2"

[plugins]
versions = "com.github.ben-manes.versions:0.51.0"